export const ActionTypes = {
  CREATE_BLOG: "CREATE_BLOG",
  READ_BLOG: "READ_BLOG",
  DELETE_BLOG: "DELETE_BLOG",
  UPDATE_BLOG: "UPDATE_BLOG",
  VIEW_UPDATE: "VIEW_UPDATE",
  UPDATE_BLOG_ID: "UPDATE_BLOG_ID",
};